### ISSUE TITLE
Getting an error when running .launch file

### ISSUE THREAD

**Issue by GilgameshD** [pulver22/QLAB#1]
When I was running these launch files, I got this error:

     ERROR: cannot launch node of type [message_to_tf/message_to_tf]: can't locate node [message_to_tf] in package [message_to_tf]

What should I do?

Thanks.

**Comment by pulver22** [comment]
Hi @GilgameshD ,

Can you provide more infos about your sistem (OS, Ros and Gazebo version).
Did you get any errors while compiling with `catkin_make`?

**Comment by GilgameshD** [comment]
I am sorry that this is not your problem. I forgot that I downloaded the package "message_to_tf" to another catkin workspace. Thanks a lot ~

**Comment by pulver22** [comment]
Happy to hear you solved your issue!
