### ISSUE TITLE
Questions about marker in Gazebo

### ISSUE THREAD

**Issue by GilgameshD** [pulver22/QLAB#2]
![image](https://user-images.githubusercontent.com/13979878/32405492-80de166a-c134-11e7-8929-aaa5d1566228.png)

Sorry, I am not familiar with gazebo.

When I run the launch file, I got this scene in Gazebo. I think the marker is at the same height of the ground plane. So what should I do to move it?

**Comment by pulver22** [comment]
Do you get any error in the ros-console?
I need to check the code but I am not sure I included the marker model in this repository. I may have forgotten it.

I will do it as soon as I can and let you know!

Edit: @GilgameshD  I checked the repo and the marker is already included. Can you lease tell me which launch file do you use?
