### ISSUE TITLE
The Gazebo environment just show an empty world with a quacopter only

### ISSUE THREAD

**Issue by ibrahimqazi** [pulver22/QLAB#5]
Hi there!
I want to this simulation but first problem is it takes a lot of time to load and second problem that after loading there an empty world with a single quad-rotor only, nothing else is on the display. What could be the possible reason for this. Thanks

**Comment by ibrahimqazi** [comment]
I tried both these commands,
`roslaunch deep_reinforced_landing drl.launch`
`roslaunch qlab_gazebo qlab.launch`
but the window appears for both is same. So approximately how much do I need to wait? I waited for more than 30 minutes but still the same window with no changes.  Thanks

**Comment by ibrahimqazi** [comment]
@pulver22 as you said the windows that appear should be empty with only the drone and, eventually, the landing marker. But I didn't see any marker just a drone, as in the **world tab** there is a marker but not shown in the main window.

**Comment by pulver22** [comment]
Hi @ibrahimqazi,

I guess that the reason why the marker is not shown is that the path to the texture is wrong. I will check as soon as I can but in the meantime, you can try to copy the folder `QLAB/qlab/qlab_gazebo/models/marker` into `~/.gazebo/models/` and re-run the code.

**Comment by ibrahimqazi** [comment]
Thanks, I copied the marker info to gazebo folder, and I can see that now. But I have one more question that after launching `roslaunch deep_reinforced_landing drl.launch`, how can we start the simulation properly, I mean do we need to publish commands on specific topics from terminal? Because UAV is already on the marker.

**Comment by pulver22** [comment]
Hi @ibrahimqazi, 

What do you want to do? The launch file only sets up correctly the virtual environment. If you want to perform some training on detection or descending you can use the files that are in `src` folder.

By default, there is no "replay" a previous experiments. I may consider to include the weights of the DQN I trained, so you can see how it works.
