### ISSUE TITLE
Gazebo Hangs at preparing world

### ISSUE THREAD

**Issue by ghost** [pulver22/QLAB#6]
I have been trying to do ```roslaunch qlab_gazebo qlab.launch``` to startup the gazebo simulator with quadcopter in it. But I am stuck at black screen with a Gazebo message saying Preparing Your World
Here are the latest logs printed on terminal
```
SpawnModel script started
[INFO] [1560874611.659303, 0.000000]: Loading model XML from ros parameter
[INFO] [1560874611.661537, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1560874612.567880, 0.000000]: Calling service /gazebo/spawn_urdf_model

```

**Comment by pulver22** [comment]
Hi @uidp1499,

for how long did you leave the Gazebo loading the environment? Can you please post the entire log, the latest lines are not helpful (they don't contains any error).

I will check asap on my system and come back to you. The first time you run the code may take a bit longer to find the model it needs.
