### ISSUE TITLE
camera issues

### ISSUE THREAD

**Issue by oussama-lab** [pulver22/QLAB#8]
hi, it's great project very helpful, so i'am tring to recive output camera infos in gazebo with this commande line:
rostopic echo /quadrotor/ardrone/camera_info , of corse after i launched the drl.launch (master),but this appear :
WARNING: no messages received and simulated time is active.
Is /clock being published?
so even with the rqt_graph node the front and bottom camera does not publish in gazebo, so is there any solution for this?

**Comment by pulver22** [comment]
Hi @oussama-lab,

If you want to get the image from the camera, the correct topic is the one called `camera_raw` or `image_raw` ( I don't have the code in front of me right now). If you echo that, you will receive the RGB image.

Please let me know if this helps!

**Comment by oussama-lab** [comment]
Hi @pulver22 ,
thanks a lot it works ,the right topic is  image_raw

**Comment by pulver22** [comment]
Good, glad you solved! I close the issue.
